/**
 * Source of truth for Connect how-to guides.
 * Maps FluideAdmin help articles → API integration guides.
 *
 * Run: node scripts/generate-guide-pages.mjs
 *      node scripts/generate-guides-index.mjs
 *      node scripts/validate-guides.mjs
 */

/** @typedef {"published" | "draft" | "planned"} GuideStatus */

export const GUIDE_CATEGORIES = [
  { id: "service-partner", label: "Service partner", navGroup: "Service partner" },
  { id: "hr", label: "HR & People", navGroup: "HR & People" },
  { id: "hr-operations", label: "HR Operations", navGroup: "HR Operations" },
  { id: "payroll", label: "Payroll", navGroup: "Payroll" },
  { id: "pay", label: "Pay", navGroup: "Pay" },
  { id: "books", label: "Books", navGroup: "Books" },
  { id: "access", label: "Access & Auth", navGroup: "Access & Auth" },
  { id: "utils", label: "Utils", navGroup: "Utils" },
  { id: "playbooks", label: "Playbooks", navGroup: "Playbooks" },
];

const PH = `  -H "X-Workspace-Id: $FLUIDE_WORKSPACE_ID" \\
  -H "X-Acting-Company-Id: $FLUIDE_COMPANY_ID"`;

const AUTH = `  -H "Authorization: Bearer $FLUIDE_ACCESS_TOKEN" \\
  -H "X-Fluide-Api-Key: $FLUIDE_API_KEY" \\
  -H "X-Fluide-Client-Id: fluide-developer"`;

/** @type {Array<import('./catalog.types').GuideEntry>} */
export const GUIDES = [
  // ── Service partner ──────────────────────────────────────────────────────
  {
    slug: "service-partner/onboard-client-company",
    categoryId: "service-partner",
    title: "Onboard a client company",
    description:
      "Create a workspace and client company for a partner integration, then store IDs for acting-client API calls.",
    adminArticleId: "partner.clients",
    status: "published",
    priority: "P0",
    icon: "building",
    partnerHeaders: false,
    permissionHints: ["partner:workspace:manage", "partner:client-company:manage"],
    prerequisites: [
      "Developer API key and machine JWT — [Authorization](/getting-started/authorization)",
      "SERVICE_PARTNER organization",
    ],
    steps: [
      {
        title: "List or create a workspace",
        body: `List workspaces, then create one if needed:\n\n\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/workspaces" \\\n${AUTH}\n\`\`\``,
      },
      {
        title: "Create the client company",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/workspaces/$FLUIDE_WORKSPACE_ID/companies" \\\n${AUTH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"name":"Acme Corp","countryCode":"CM","currency":"XAF"}'\n\`\`\`\n\nSave \`companyId\` for acting-client headers.`,
      },
    ],
    tips: ["A Default workspace is auto-created during SERVICE_PARTNER onboarding."],
    troubleshooting: [
      { problem: "`403` partner:workspace:manage", resolution: "Complete developer onboarding as SERVICE_PARTNER." },
    ],
    related: ["guides/service-partner/act-as-client", "guides/hr/add-employee"],
  },
  {
    slug: "service-partner/self-onboarding-link",
    categoryId: "service-partner",
    title: "Issue a self-onboarding link",
    description: "Generate a one-time URL so a merchant completes their own company profile.",
    adminArticleId: "partner.clients",
    status: "published",
    priority: "P0",
    icon: "link",
    partnerHeaders: false,
    permissionHints: ["partner:client-company:manage"],
    prerequisites: ["Workspace exists — [Onboard a client company](/guides/service-partner/onboard-client-company)"],
    steps: [
      {
        title: "Issue the link",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/workspaces/$FLUIDE_WORKSPACE_ID/companies/onboarding-link" \\\n${AUTH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"name":"Pending — Acme Corp","ttlSeconds":604800}'\n\`\`\``,
      },
    ],
    tips: ["`companyId` is stable from link issuance — store acting-client headers immediately."],
    troubleshooting: [],
    related: ["guides/service-partner/onboard-client-company"],
  },
  {
    slug: "service-partner/client-kyb",
    categoryId: "service-partner",
    title: "Submit client KYB",
    description: "Upload KYB documents and submit partner-mediated compliance review for a client company.",
    adminArticleId: "partner.compliance",
    status: "published",
    priority: "P0",
    icon: "shield-check",
    partnerHeaders: false,
    permissionHints: ["partner:client-company:manage"],
    prerequisites: ["Client company under a workspace"],
    steps: [
      {
        title: "Check KYB state",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/workspaces/$FLUIDE_WORKSPACE_ID/companies/$FLUIDE_COMPANY_ID/kyb" \\\n${AUTH}\n\`\`\``,
      },
      {
        title: "Upload documents and submit",
        body: "Upload required files per KYB state, then `POST .../kyb/submit`. See [Auth API reference](/api-reference/auth).",
      },
    ],
    tips: ["Firm KYB uses `/api/v1/onboarding/kyb/*`; client KYB uses workspace company routes."],
    troubleshooting: [],
    related: ["guides/service-partner/partner-firm-kyb"],
  },
  {
    slug: "service-partner/act-as-client",
    categoryId: "service-partner",
    title: "Act as a client via API",
    description: "Scope product API requests to a specific merchant using acting-client headers.",
    adminArticleId: "partner.act-as-client",
    status: "published",
    priority: "P0",
    icon: "user-check",
    partnerHeaders: true,
    permissionHints: ["partner:client:act-as"],
    prerequisites: ["Machine JWT and merchant workspaceId + companyId"],
    steps: [
      {
        title: "Call a product API with acting headers",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/hr/employees" \\\n${AUTH} \\\n${PH}\n\`\`\``,
      },
    ],
    tips: ["Both acting headers must be sent together on every product API call."],
    troubleshooting: [
      { problem: "Wrong merchant data", resolution: "Verify company.workspaceId matches X-Workspace-Id." },
    ],
    related: ["getting-started/multi-tenancy"],
  },
  {
    slug: "service-partner/manage-workspaces",
    categoryId: "service-partner",
    title: "Manage workspaces",
    description: "Create, list, and organize partner workspaces that group client companies.",
    adminArticleId: "partner.workspaces",
    status: "published",
    priority: "P1",
    icon: "folder-tree",
    partnerHeaders: false,
    permissionHints: ["partner:workspace:manage"],
    prerequisites: ["SERVICE_PARTNER org and machine JWT"],
    steps: [
      {
        title: "List workspaces",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/workspaces" \\\n${AUTH}\n\`\`\``,
      },
      {
        title: "Create a workspace",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/workspaces" \\\n${AUTH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"name":"Sandbox merchants","metadata":{"visibility":"public"}}'\n\`\`\``,
      },
      {
        title: "Update or delete",
        body: "Use `PATCH /api/v1/workspaces/{id}` or `DELETE` per [Auth API reference](/api-reference/auth). Private workspaces restrict visibility to owners/admins and `workspace_member` rows.",
      },
    ],
    tips: ["Use separate workspaces for sandbox vs production merchants."],
    troubleshooting: [],
    related: ["guides/service-partner/onboard-client-company"],
  },
  {
    slug: "service-partner/partner-firm-kyb",
    categoryId: "service-partner",
    title: "Complete partner firm KYB",
    description: "Submit Know Your Business verification for your SERVICE_PARTNER organization.",
    adminArticleId: "partner.verification",
    status: "published",
    priority: "P1",
    icon: "badge-check",
    partnerHeaders: false,
    permissionHints: ["onboarding:kyb:write"],
    prerequisites: ["Partner org onboarding started"],
    steps: [
      {
        title: "Get KYB state",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/onboarding/kyb" \\\n${AUTH}\n\`\`\``,
      },
      {
        title: "Upload and submit",
        body: "Upload documents via onboarding KYB routes, then `POST /api/v1/onboarding/kyb/submit`. Distinct from [client KYB](/guides/service-partner/client-kyb).",
      },
    ],
    tips: ["Firm KYB must be approved before production API access."],
    troubleshooting: [],
    related: ["guides/service-partner/client-kyb"],
  },
  {
    slug: "service-partner/manage-partner-team",
    categoryId: "service-partner",
    title: "Manage partner team members",
    description: "Invite and assign roles to staff in your SERVICE_PARTNER organization.",
    adminArticleId: "partner.team",
    status: "published",
    priority: "P2",
    icon: "users",
    partnerHeaders: false,
    permissionHints: ["org:members:write"],
    prerequisites: ["Org admin or owner role"],
    steps: [
      {
        title: "List members",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/organizations/$ORG_ID/members" \\\n${AUTH}\n\`\`\``,
      },
      {
        title: "Invite a member",
        body: "Use organization member invite endpoints in [Auth API reference](/api-reference/auth). Assign roles with `partner:client:act-as` for staff who operate on client data.",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/access/assign-org-roles"],
  },
  {
    slug: "service-partner/list-partner-transactions",
    categoryId: "service-partner",
    title: "List partner transactions",
    description: "View payment and wallet transactions across client companies in your partner portfolio.",
    adminArticleId: "partner.transactions",
    status: "published",
    priority: "P2",
    icon: "receipt",
    partnerHeaders: true,
    permissionHints: ["pay:transactions:read"],
    prerequisites: ["Acting-client headers for the target merchant"],
    steps: [
      {
        title: "List transactions",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/transactions" \\\n${AUTH} \\\n${PH}\n\`\`\``,
      },
    ],
    tips: ["Filter by date range and status in query params — see [Pay API reference](/api-reference/pay)."],
    troubleshooting: [],
    related: ["guides/pay/create-wallet-types"],
  },

  // ── HR & People ──────────────────────────────────────────────────────────
  {
    slug: "hr/add-employee",
    categoryId: "hr",
    title: "Add an employee",
    description: "Create a single employee record via the HR API — canonical source for payroll.",
    adminArticleId: "employees.add-single",
    status: "published",
    priority: "P0",
    icon: "user-plus",
    partnerHeaders: true,
    permissionHints: ["hr:employees:write"],
    prerequisites: ["API credentials; partner acting headers when ISV"],
    steps: [
      {
        title: "Create employee",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/hr/employees" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"firstName":"Ada","lastName":"Lovelace","email":"ada@example.com","employeeCode":"EMP-001"}'\n\`\`\``,
      },
    ],
    tips: ["Use `onboard-with-staff` when the employee also needs a FluideAuth seat."],
    troubleshooting: [
      { problem: "Employee not in Payroll", resolution: "See [HR → Payroll](/guides/playbooks/hr-to-payroll)." },
    ],
    related: ["guides/playbooks/hr-to-payroll", "guides/hr/manage-employment-contracts"],
  },
  {
    slug: "hr/bulk-import-employees",
    categoryId: "hr",
    title: "Bulk import employees",
    description: "Download the HR import template and upload a spreadsheet of employees.",
    adminArticleId: "employees.bulk-import",
    status: "published",
    priority: "P1",
    icon: "file-import",
    partnerHeaders: true,
    permissionHints: ["hr:employees:write"],
    prerequisites: ["Filled import spreadsheet"],
    steps: [
      {
        title: "Download template",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/hr/employees/import-template" \\\n${AUTH} \\\n${PH} -o template.xlsx\n\`\`\``,
      },
      {
        title: "Upload",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/hr/employees/import" \\\n${AUTH} \\\n${PH} -F "file=@employees.xlsx"\n\`\`\``,
      },
    ],
    tips: ["Test with 5–10 rows in sandbox first."],
    troubleshooting: [],
    related: ["guides/hr/add-employee"],
  },
  {
    slug: "hr/configure-payout-rails",
    categoryId: "hr",
    title: "Configure employee payout rails",
    description: "Set up bank or mobile-money payout rails for employees via HR API.",
    adminArticleId: "employees.payout-rails-import",
    status: "published",
    priority: "P1",
    icon: "credit-card",
    partnerHeaders: true,
    permissionHints: ["hr:employees:write"],
    prerequisites: ["Employee record exists"],
    steps: [
      {
        title: "Configure payout rail",
        body: "Use employee payout configuration endpoints under `/api/v1/hr/employees/{id}` in [HR API reference](/api-reference/hr). Required before payroll disbursement.",
      },
    ],
    tips: ["Rails must match Pay provider capabilities for the company's country."],
    troubleshooting: [],
    related: ["guides/pay/first-payroll-disbursement"],
  },
  {
    slug: "hr/update-employee",
    categoryId: "hr",
    title: "Update an employee profile",
    description: "Patch employee personal, employment, and contact details via API.",
    adminArticleId: "employees.edit-profile",
    status: "published",
    priority: "P2",
    icon: "user-pen",
    partnerHeaders: true,
    permissionHints: ["hr:employees:write"],
    prerequisites: ["Employee UUID"],
    steps: [
      {
        title: "Patch employee",
        body: `\`\`\`bash\ncurl -sS -X PATCH "$FLUIDE_BASE_URL/api/v1/hr/employees/$EMPLOYEE_ID" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"jobTitle":"Senior Engineer"}'\n\`\`\``,
      },
    ],
    tips: ["Updates trigger Payroll mirror refresh."],
    troubleshooting: [],
    related: ["guides/hr/add-employee"],
  },
  {
    slug: "hr/download-employee-cv",
    categoryId: "hr",
    title: "Download employee CV",
    description: "Export an employee CV document via HR or Utils document APIs.",
    adminArticleId: "employees.download-cv",
    status: "published",
    priority: "P3",
    icon: "file-pdf",
    partnerHeaders: true,
    permissionHints: ["hr:employees:read"],
    prerequisites: ["Employee with CV attachment"],
    steps: [
      {
        title: "Get CV",
        body: "Use employee document endpoints in [HR API reference](/api-reference/hr) or [Utils file APIs](/api-reference/utils).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/utils/upload-and-retrieve-files"],
  },

  // ── HR Operations ────────────────────────────────────────────────────────
  {
    slug: "hr-operations/manage-employment-contracts",
    categoryId: "hr-operations",
    title: "Manage employment contracts",
    description: "Create and update employment contracts that drive payroll eligibility.",
    adminArticleId: "contracts.manage",
    status: "published",
    priority: "P1",
    icon: "file-contract",
    partnerHeaders: true,
    permissionHints: ["hr:contracts:write"],
    prerequisites: ["Employee exists in HR"],
    steps: [
      {
        title: "Create contract",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/hr/employment-contracts" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"employeeId":"'$EMPLOYEE_ID'","startDate":"2026-01-01","employmentType":"FULL_TIME"}'\n\`\`\``,
      },
    ],
    tips: ["Active contract required for payroll run inclusion."],
    troubleshooting: [],
    related: ["guides/payroll/run-payroll"],
  },
  {
    slug: "hr-operations/request-leave",
    categoryId: "hr-operations",
    title: "Request leave",
    description: "Submit and track employee leave requests via the HR API.",
    adminArticleId: "leave.request",
    status: "published",
    priority: "P1",
    icon: "calendar",
    partnerHeaders: true,
    permissionHints: ["hr:leave:write"],
    prerequisites: ["Leave policy configured"],
    steps: [
      {
        title: "Create leave request",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/hr/leave/requests" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"employeeId":"'$EMPLOYEE_ID'","leaveTypeId":"'$LEAVE_TYPE_ID'","startDate":"2026-08-01","endDate":"2026-08-05"}'\n\`\`\``,
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/hr-operations/configure-leave-policy"],
  },
  {
    slug: "hr-operations/clock-attendance",
    categoryId: "hr-operations",
    title: "Clock attendance",
    description: "Record clock-in and clock-out events for attendance tracking.",
    adminArticleId: "attendance.clock",
    status: "published",
    priority: "P2",
    icon: "clock",
    partnerHeaders: true,
    permissionHints: ["hr:attendance:write"],
    prerequisites: ["Employee exists"],
    steps: [
      {
        title: "Record clock event",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/hr/attendance/events" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"employeeId":"'$EMPLOYEE_ID'","eventType":"CLOCK_IN"}'\n\`\`\``,
      },
    ],
    tips: [],
    troubleshooting: [],
    related: [],
  },
  {
    slug: "hr-operations/configure-leave-policy",
    categoryId: "hr-operations",
    title: "Configure leave policy",
    description: "Set up leave types, accrual rules, and approval workflows.",
    adminArticleId: "hr.leave-policy",
    status: "published",
    priority: "P2",
    icon: "calendar-days",
    partnerHeaders: true,
    permissionHints: ["hr:leave:admin"],
    prerequisites: ["HR admin permissions"],
    steps: [
      {
        title: "Manage leave types",
        body: "Use `/api/v1/hr/leave/types` and policy endpoints in [HR API reference](/api-reference/hr).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/hr-operations/request-leave"],
  },
  {
    slug: "hr-operations/run-performance-cycle",
    categoryId: "hr-operations",
    title: "Run a performance cycle",
    description: "Create and manage performance review cycles via API.",
    adminArticleId: "hr.performance",
    status: "published",
    priority: "P3",
    icon: "chart-line",
    partnerHeaders: true,
    permissionHints: ["hr:performance:write"],
    prerequisites: ["Performance module enabled"],
    steps: [
      {
        title: "Create cycle",
        body: "Use `/api/v1/hr/performance` endpoints in [HR API reference](/api-reference/hr).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: [],
  },
  {
    slug: "hr-operations/offboard-employee",
    categoryId: "hr-operations",
    title: "Offboard an employee",
    description: "Deactivate an employee and close out contracts and access.",
    adminArticleId: "hr.offboarding",
    status: "published",
    priority: "P2",
    icon: "user-minus",
    partnerHeaders: true,
    permissionHints: ["hr:employees:write"],
    prerequisites: ["Employee active in HR"],
    steps: [
      {
        title: "End contract and deactivate",
        body: "Terminate employment contract, then patch employee `isActive: false`. See HR employment-contract and employee endpoints.",
      },
    ],
    tips: ["Complete final payroll run before offboarding if applicable."],
    troubleshooting: [],
    related: ["guides/hr-operations/manage-employment-contracts"],
  },

  // ── Payroll ──────────────────────────────────────────────────────────────
  {
    slug: "payroll/run-payroll",
    categoryId: "payroll",
    title: "Run payroll",
    description: "Create, calculate, approve, and complete a payroll run via API.",
    adminArticleId: "payroll.run",
    status: "published",
    priority: "P0",
    icon: "wallet",
    partnerHeaders: true,
    permissionHints: ["payroll:runs:write", "payroll:runs:approve"],
    prerequisites: ["Employees mirrored in Payroll"],
    steps: [
      {
        title: "Create and process run",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/payroll/payroll" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"periodStart":"2026-06-01","periodEnd":"2026-06-30"}'\n\`\`\``,
      },
    ],
    tips: ["See [Payroll API reference](/api-reference/payroll) for calculate, approve, and complete steps."],
    troubleshooting: [],
    related: ["guides/playbooks/payroll-to-books"],
  },
  {
    slug: "payroll/configure-payroll-settings",
    categoryId: "payroll",
    title: "Configure payroll settings",
    description: "Set pay frequency, tax rules, and payroll configuration for a company.",
    adminArticleId: "payroll.settings",
    status: "published",
    priority: "P1",
    icon: "gear",
    partnerHeaders: true,
    permissionHints: ["payroll:settings:write"],
    prerequisites: ["Company onboarded"],
    steps: [
      {
        title: "Get and update settings",
        body: "Use payroll settings endpoints in [Payroll API reference](/api-reference/payroll).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/payroll/run-payroll"],
  },
  {
    slug: "payroll/payroll-chart-of-accounts",
    categoryId: "payroll",
    title: "Payroll chart of accounts",
    description: "Map payroll components to GL accounts before Books integration.",
    adminArticleId: "payroll.chart-of-accounts",
    status: "published",
    priority: "P1",
    icon: "list-tree",
    partnerHeaders: true,
    permissionHints: ["payroll:settings:write"],
    prerequisites: ["Books subsidiary exists"],
    steps: [
      {
        title: "Configure mappings",
        body: "Set payroll account mappings via Books or Payroll APIs — see [Payroll → Books](/guides/playbooks/payroll-to-books).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/playbooks/payroll-to-books"],
  },

  // ── Pay ──────────────────────────────────────────────────────────────────
  {
    slug: "pay/create-wallet-types",
    categoryId: "pay",
    title: "Create wallet types",
    description: "Provision operating and other wallet types for a client company.",
    adminArticleId: "wallets.create-types",
    status: "published",
    priority: "P1",
    icon: "wallet",
    partnerHeaders: true,
    permissionHints: ["pay:wallets:write"],
    prerequisites: ["Company exists; KYB may be required"],
    steps: [
      {
        title: "Create wallet",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/accounts/wallets" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"walletType":"OPERATING","currency":"XAF"}'\n\`\`\``,
      },
    ],
    tips: ["Default operating wallet is auto-provisioned when a partner creates a client company."],
    troubleshooting: [],
    related: ["guides/pay/first-payroll-disbursement"],
  },
  {
    slug: "pay/first-payroll-disbursement",
    categoryId: "pay",
    title: "First payroll disbursement",
    description: "Disburse net pay from a completed payroll run to employee payout rails.",
    adminArticleId: "playbooks.pay.first-payroll-disburse",
    status: "published",
    priority: "P0",
    icon: "money-bill-transfer",
    partnerHeaders: true,
    permissionHints: ["payroll:runs:approve", "pay:transactions:write"],
    prerequisites: ["Completed payroll run; employee payout rails configured"],
    steps: [
      {
        title: "Initiate disbursement",
        body: "After payroll run completes, trigger disbursement via Payroll → Pay integration. See [Run payroll](/guides/payroll/run-payroll) and [Pay API reference](/api-reference/pay).",
      },
      {
        title: "Verify transactions",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/transactions" \\\n${AUTH} \\\n${PH}\n\`\`\``,
      },
    ],
    tips: ["Ensure operating wallet has sufficient balance."],
    troubleshooting: [],
    related: ["guides/playbooks/partner-onboard-to-first-payroll"],
  },
  {
    slug: "pay/create-payment-link",
    categoryId: "pay",
    title: "Create a payment link",
    description: "Generate a checkout session or payment link for collecting customer payments.",
    adminArticleId: "playbooks.pay.payment-links",
    status: "published",
    priority: "P1",
    icon: "link",
    partnerHeaders: true,
    permissionHints: ["pay:checkout:write"],
    prerequisites: ["Pay provider configured"],
    steps: [
      {
        title: "Create checkout session",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/checkout/sessions" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"amount":50000,"currency":"XAF"}'\n\`\`\``,
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/playbooks/invoice-to-cash-collection"],
  },
  {
    slug: "pay/collect-invoice-payment",
    categoryId: "pay",
    title: "Collect invoice payment",
    description: "Record payment against a Books invoice via Pay integration.",
    adminArticleId: "playbooks.pay.invoice-collections",
    status: "published",
    priority: "P2",
    icon: "hand-holding-dollar",
    partnerHeaders: true,
    permissionHints: ["books:invoices:write", "pay:transactions:write"],
    prerequisites: ["Open invoice in Books"],
    steps: [
      {
        title: "Record payment",
        body: "Use invoice payment endpoints in [Books API reference](/api-reference/books) and Pay transaction APIs.",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/books/create-invoice", "guides/playbooks/invoice-to-cash-collection"],
  },
  {
    slug: "pay/disburse-bill-payment",
    categoryId: "pay",
    title: "Disburse a bill payment",
    description: "Pay an approved vendor bill from your operating wallet.",
    adminArticleId: "playbooks.pay.bill-disburse",
    status: "published",
    priority: "P2",
    icon: "file-invoice-dollar",
    partnerHeaders: true,
    permissionHints: ["books:bills:write", "pay:transactions:write"],
    prerequisites: ["Approved bill in Books"],
    steps: [
      {
        title: "Initiate bill payment",
        body: "Use bill payment and transfer endpoints in [Pay API reference](/api-reference/pay).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/books/record-bill"],
  },
  {
    slug: "pay/export-bank-files",
    categoryId: "pay",
    title: "Export bank payment files",
    description: "Generate bank upload files for bulk payroll or vendor disbursements.",
    adminArticleId: "playbooks.pay.bank-files-export",
    status: "published",
    priority: "P3",
    icon: "file-export",
    partnerHeaders: true,
    permissionHints: ["pay:transactions:read"],
    prerequisites: ["Scheduled disbursement batch"],
    steps: [
      {
        title: "Export file",
        body: "Use bank file export endpoints in [Pay API reference](/api-reference/pay) for your provider format.",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/pay/first-payroll-disbursement"],
  },

  // ── Books ────────────────────────────────────────────────────────────────
  {
    slug: "books/books-overview",
    categoryId: "books",
    title: "Books overview for integrators",
    description: "Understand accounting modules, subsidiaries, and API layout for Fluide Books.",
    adminArticleId: "financials.overview",
    status: "published",
    priority: "P1",
    icon: "book",
    partnerHeaders: true,
    permissionHints: ["books:read"],
    prerequisites: ["API credentials"],
    steps: [
      {
        title: "Verify connectivity",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/chart-of-accounts" \\\n${AUTH} \\\n${PH}\n\`\`\``,
      },
    ],
    tips: ["Books routes use `/api/v1/*` without a product prefix."],
    troubleshooting: [],
    related: ["guides/books/chart-of-accounts"],
  },
  {
    slug: "books/create-invoice",
    categoryId: "books",
    title: "Create an invoice",
    description: "Create and send a customer invoice via the Books API.",
    adminArticleId: "financials.invoices",
    status: "published",
    priority: "P1",
    icon: "file-invoice",
    partnerHeaders: true,
    permissionHints: ["books:invoices:write"],
    prerequisites: ["Customer business partner exists"],
    steps: [
      {
        title: "Create invoice",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/invoices" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{}'\n\`\`\`\n\nSee [Books API reference](/api-reference/books) for line items and tax.`,
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/books/record-invoice-payment"],
  },
  {
    slug: "books/record-bill",
    categoryId: "books",
    title: "Record a bill",
    description: "Create a vendor bill for accounts payable.",
    adminArticleId: "financials.bills",
    status: "published",
    priority: "P1",
    icon: "receipt",
    partnerHeaders: true,
    permissionHints: ["books:bills:write"],
    prerequisites: ["Vendor business partner"],
    steps: [
      {
        title: "Create bill",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/bills" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{}'\n\`\`\``,
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/books/bill-approval-workflow"],
  },
  {
    slug: "books/post-journal-entry",
    categoryId: "books",
    title: "Post a journal entry",
    description: "Create and post double-entry journal entries to the general ledger.",
    adminArticleId: "financials.journal-entries",
    status: "published",
    priority: "P1",
    icon: "book-open",
    partnerHeaders: true,
    permissionHints: ["books:journal:write"],
    prerequisites: ["Chart of accounts configured"],
    steps: [
      {
        title: "Create journal entry",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/journal-entries" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{}'\n\`\`\``,
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/playbooks/payroll-to-books"],
  },
  {
    slug: "books/chart-of-accounts",
    categoryId: "books",
    title: "Chart of accounts",
    description: "List and create GL accounts in the account hierarchy.",
    adminArticleId: "financials.chart-of-accounts",
    status: "published",
    priority: "P1",
    icon: "sitemap",
    partnerHeaders: true,
    permissionHints: ["books:coa:write"],
    prerequisites: ["Subsidiary selected"],
    steps: [
      {
        title: "List accounts",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/chart-of-accounts" \\\n${AUTH} \\\n${PH}\n\`\`\``,
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/books/books-overview"],
  },
  {
    slug: "books/manage-business-partners",
    categoryId: "books",
    title: "Manage business partners",
    description: "Create customers and vendors used on invoices and bills.",
    adminArticleId: "financials.business-partners",
    status: "published",
    priority: "P2",
    icon: "handshake",
    partnerHeaders: true,
    permissionHints: ["books:partners:write"],
    prerequisites: [],
    steps: [
      {
        title: "Create partner",
        body: "Use `/api/v1/business-partners` in [Books API reference](/api-reference/books).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/books/create-invoice"],
  },
  {
    slug: "books/bill-approval-workflow",
    categoryId: "books",
    title: "Bill approval workflow",
    description: "Submit bills for approval and track approval status via API.",
    adminArticleId: "financials.bill-approvals",
    status: "published",
    priority: "P2",
    icon: "check-double",
    partnerHeaders: true,
    permissionHints: ["books:bills:approve"],
    prerequisites: ["Bill in draft or pending state"],
    steps: [
      {
        title: "Submit for approval",
        body: "Use bill approval endpoints in [Books API reference](/api-reference/books).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/books/record-bill", "guides/pay/disburse-bill-payment"],
  },
  {
    slug: "books/recurring-journal-entries",
    categoryId: "books",
    title: "Recurring journal entries",
    description: "Set up automated recurring GL entries.",
    adminArticleId: "financials.recurring-entries",
    status: "published",
    priority: "P3",
    icon: "rotate",
    partnerHeaders: true,
    permissionHints: ["books:journal:write"],
    prerequisites: [],
    steps: [
      {
        title: "Create recurring template",
        body: "Use recurring journal entry endpoints in [Books API reference](/api-reference/books).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/books/post-journal-entry"],
  },
  {
    slug: "books/record-invoice-payment",
    categoryId: "books",
    title: "Record invoice payment",
    description: "Apply a payment to an open invoice in Books.",
    adminArticleId: "financials.invoice-payments",
    status: "published",
    priority: "P2",
    icon: "coins",
    partnerHeaders: true,
    permissionHints: ["books:invoices:write"],
    prerequisites: ["Open invoice"],
    steps: [
      {
        title: "Record payment",
        body: "Use invoice payment endpoints in [Books API reference](/api-reference/books).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/pay/collect-invoice-payment"],
  },
  {
    slug: "books/bank-reconciliation",
    categoryId: "books",
    title: "Bank reconciliation",
    description: "Match bank transactions to ledger entries.",
    adminArticleId: "financials.reconciliation",
    status: "published",
    priority: "P2",
    icon: "scale-balanced",
    partnerHeaders: true,
    permissionHints: ["books:reconciliation:write"],
    prerequisites: ["Bank feed or imported statement"],
    steps: [
      {
        title: "Start reconciliation",
        body: "Use reconciliation endpoints in [Books API reference](/api-reference/books).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: [],
  },
  {
    slug: "books/financial-statements",
    categoryId: "books",
    title: "Financial statements",
    description: "Generate P&L, balance sheet, and cash flow reports via API.",
    adminArticleId: "financials.statements-reports",
    status: "published",
    priority: "P2",
    icon: "chart-pie",
    partnerHeaders: true,
    permissionHints: ["books:reports:read"],
    prerequisites: ["Posted journal entries for the period"],
    steps: [
      {
        title: "Fetch statements",
        body: "Use reporting endpoints in [Books API reference](/api-reference/books). Export PDFs via [Utils](/guides/utils/generate-payslip-pdf) document patterns.",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/books/books-overview"],
  },
  {
    slug: "books/configure-tax-settings",
    categoryId: "books",
    title: "Configure tax settings",
    description: "Set tax codes and rates for invoices and bills.",
    adminArticleId: "financials.tax-settings",
    status: "published",
    priority: "P3",
    icon: "percent",
    partnerHeaders: true,
    permissionHints: ["books:settings:write"],
    prerequisites: [],
    steps: [
      {
        title: "Configure taxes",
        body: "Use tax settings endpoints in [Books API reference](/api-reference/books).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/books/create-invoice"],
  },

  // ── Access ───────────────────────────────────────────────────────────────
  {
    slug: "access/machine-token-and-scopes",
    categoryId: "access",
    title: "Machine tokens and scopes",
    description: "Exchange API keys for JWTs and understand permission scoping for integrations.",
    adminArticleId: null,
    status: "published",
    priority: "P1",
    icon: "key",
    partnerHeaders: false,
    permissionHints: [],
    prerequisites: ["Developer API key from Connect"],
    steps: [
      {
        title: "Token exchange",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/authorize/token" \\\n  -H "X-Fluide-Api-Key: $FLUIDE_API_KEY" \\\n  -H "X-Fluide-Api-Secret: $FLUIDE_API_SECRET" \\\n  -H "X-Fluide-Client-Id: fluide-developer"\n\`\`\``,
      },
    ],
    tips: ["See [Authorization](/getting-started/authorization) for full header reference."],
    troubleshooting: [],
    related: ["getting-started/authorization", "auth/rbac"],
  },
  {
    slug: "access/create-custom-role",
    categoryId: "access",
    title: "Create a custom org role",
    description: "Define a custom role with specific permission strings.",
    adminArticleId: "rbac.roles-create",
    status: "published",
    priority: "P2",
    icon: "shield",
    partnerHeaders: false,
    permissionHints: ["org:roles:write"],
    prerequisites: ["Org admin"],
    steps: [
      {
        title: "Create role",
        body: "Use organization custom role endpoints in [Auth API reference](/api-reference/auth). See also [RBAC](/auth/rbac).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["auth/rbac"],
  },
  {
    slug: "access/assign-org-roles",
    categoryId: "access",
    title: "Assign org roles",
    description: "Assign roles to organization members.",
    adminArticleId: "rbac.roles-assign",
    status: "published",
    priority: "P2",
    icon: "user-tag",
    partnerHeaders: false,
    permissionHints: ["org:members:write"],
    prerequisites: ["Custom or built-in role exists"],
    steps: [
      {
        title: "Assign role",
        body: "Patch member role via `/api/v1/organizations/{id}/members` in [Auth API reference](/api-reference/auth).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/access/create-custom-role"],
  },
  {
    slug: "access/check-permissions",
    categoryId: "access",
    title: "Check permissions",
    description: "Validate session and inspect effective permissions for debugging.",
    adminArticleId: "rbac.roles-permissions",
    status: "published",
    priority: "P2",
    icon: "list-check",
    partnerHeaders: false,
    permissionHints: [],
    prerequisites: ["Valid session or machine JWT"],
    steps: [
      {
        title: "Validate session",
        body: `\`\`\`bash\ncurl -sS "$FLUIDE_BASE_URL/api/v1/auth/me" \\\n${AUTH}\n\`\`\`\n\nInspect \`orgMemberRole\` and permissions in the response. See [RBAC](/auth/rbac).`,
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["auth/rbac"],
  },

  // ── Utils ────────────────────────────────────────────────────────────────
  {
    slug: "utils/generate-payslip-pdf",
    categoryId: "utils",
    title: "Generate payslip PDF",
    description: "Generate a payslip PDF and retrieve a public URL via Utils.",
    adminArticleId: null,
    status: "published",
    priority: "P1",
    icon: "file-pdf",
    partnerHeaders: true,
    permissionHints: ["payroll:payslips:read"],
    prerequisites: ["Payslip exists from completed payroll run"],
    steps: [
      {
        title: "Generate PDF",
        body: `\`\`\`bash\ncurl -sS -X POST "$FLUIDE_BASE_URL/api/v1/app/documents/payslips" \\\n${AUTH} \\\n${PH} \\\n  -H "Content-Type: application/json" \\\n  -d '{"payslipId":"'$PAYSLIP_ID'"}'\n\`\`\``,
      },
    ],
    tips: ["Idempotent per payslipId unless `force=true` after payroll corrections."],
    troubleshooting: [],
    related: ["guides/playbooks/hire-to-payslip"],
  },
  {
    slug: "utils/send-notification",
    categoryId: "utils",
    title: "Send a notification",
    description: "Send email, SMS, or push notifications via Utils.",
    adminArticleId: null,
    status: "published",
    priority: "P2",
    icon: "bell",
    partnerHeaders: true,
    permissionHints: ["utils:notifications:write"],
    prerequisites: [],
    steps: [
      {
        title: "Send notification",
        body: "Use notification endpoints under `/api/v1/app/notifications` in [Utils API reference](/api-reference/utils).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: [],
  },
  {
    slug: "utils/upload-and-retrieve-files",
    categoryId: "utils",
    title: "Upload and retrieve files",
    description: "Store and fetch files via the Utils file API.",
    adminArticleId: null,
    status: "published",
    priority: "P2",
    icon: "folder-open",
    partnerHeaders: true,
    permissionHints: ["utils:files:write"],
    prerequisites: [],
    steps: [
      {
        title: "Upload file",
        body: "Use file upload endpoints in [Utils API reference](/api-reference/utils).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: [],
  },

  // ── Playbooks ────────────────────────────────────────────────────────────
  {
    slug: "playbooks/hr-to-payroll",
    categoryId: "playbooks",
    title: "HR → Payroll employee sync",
    description: "How HR mirrors employees into Payroll after API create.",
    adminArticleId: null,
    status: "published",
    priority: "P0",
    icon: "arrow-right",
    partnerHeaders: true,
    permissionHints: [],
    prerequisites: [],
    steps: [
      {
        title: "Create in HR, verify in Payroll",
        body: "HR \\`employees.id\\` equals Payroll mirror id. See [HR payroll integration](/hr/payroll-integration).",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/hr/add-employee"],
  },
  {
    slug: "playbooks/payroll-to-books",
    categoryId: "playbooks",
    title: "Payroll → Books GL posting",
    description: "GL mappings and journal posting after payroll completes.",
    adminArticleId: null,
    status: "published",
    priority: "P0",
    icon: "book",
    partnerHeaders: true,
    permissionHints: [],
    prerequisites: [],
    steps: [
      {
        title: "Configure mappings and complete run",
        body: "Payroll publishes \\`PAYROLL_RUN_COMPLETED\\`; Books posts journal. Required \\`componentCode\\` mappings listed in guide body.",
      },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/payroll/run-payroll"],
  },
  {
    slug: "playbooks/partner-onboard-to-first-employee",
    categoryId: "playbooks",
    title: "Partner onboard to first employee",
    description: "End-to-end: workspace → company → acting headers → HR employee.",
    adminArticleId: null,
    status: "published",
    priority: "P0",
    icon: "route",
    partnerHeaders: true,
    permissionHints: [],
    prerequisites: ["Developer API credentials"],
    steps: [
      { title: "Create workspace and company", body: "Follow [Onboard a client company](/guides/service-partner/onboard-client-company)." },
      { title: "Add employee with acting headers", body: "Follow [Add an employee](/guides/hr/add-employee)." },
      { title: "Verify Payroll mirror", body: "Follow [HR → Payroll](/guides/playbooks/hr-to-payroll)." },
    ],
    tips: [],
    troubleshooting: [],
    related: ["guides/playbooks/partner-onboard-to-first-payroll"],
  },
  {
    slug: "playbooks/partner-onboard-to-first-payroll",
    categoryId: "playbooks",
    title: "Partner onboard to first payroll",
    description: "Full ISV path from merchant onboarding through first payroll run.",
    adminArticleId: null,
    status: "published",
    priority: "P0",
    icon: "flag-checkered",
    partnerHeaders: true,
    permissionHints: [],
    prerequisites: ["Partner account with API key"],
    steps: [
      { title: "Onboard merchant", body: "[Onboard client](/guides/service-partner/onboard-client-company) + optional [KYB](/guides/service-partner/client-kyb)." },
      { title: "HR setup", body: "[Employee](/guides/hr/add-employee) + [contract](/guides/hr-operations/manage-employment-contracts) + [payout rails](/guides/hr/configure-payout-rails)." },
      { title: "Payroll config and run", body: "[Settings](/guides/payroll/configure-payroll-settings) → [Run payroll](/guides/payroll/run-payroll)." },
      { title: "Disburse", body: "[First payroll disbursement](/guides/pay/first-payroll-disbursement)." },
    ],
    tips: [],
    troubleshooting: [],
    related: [],
  },
  {
    slug: "playbooks/hire-to-payslip",
    categoryId: "playbooks",
    title: "Hire to payslip",
    description: "HR create → payroll run → payslip PDF delivery.",
    adminArticleId: null,
    status: "published",
    priority: "P1",
    icon: "file-lines",
    partnerHeaders: true,
    permissionHints: [],
    prerequisites: [],
    steps: [
      { title: "Create employee and run payroll", body: "See [Run payroll](/guides/payroll/run-payroll)." },
      { title: "Generate PDF", body: "[Generate payslip PDF](/guides/utils/generate-payslip-pdf)." },
    ],
    tips: [],
    troubleshooting: [],
    related: [],
  },
  {
    slug: "playbooks/invoice-to-cash-collection",
    categoryId: "playbooks",
    title: "Invoice to cash collection",
    description: "Books invoice → Pay payment link → record payment.",
    adminArticleId: null,
    status: "published",
    priority: "P2",
    icon: "money-bill-wave",
    partnerHeaders: true,
    permissionHints: [],
    prerequisites: [],
    steps: [
      { title: "Create invoice", body: "[Create an invoice](/guides/books/create-invoice)." },
      { title: "Collect payment", body: "[Payment link](/guides/pay/create-payment-link) or [record payment](/guides/books/record-invoice-payment)." },
    ],
    tips: [],
    troubleshooting: [],
    related: [],
  },
];

export function getPublishedGuides() {
  return GUIDES.filter((g) => g.status === "published");
}

export function getGuidesByCategory(categoryId) {
  return GUIDES.filter((g) => g.categoryId === categoryId);
}

export function getNavPages() {
  const pages = ["guides/index"];
  for (const cat of GUIDE_CATEGORIES) {
    const guides = getGuidesByCategory(cat.id).filter((g) => g.status === "published");
    for (const g of guides) {
      pages.push(`guides/${g.slug}`);
    }
  }
  return pages;
}
